### ISSUE TITLE
Bug with sequence plugin

### ISSUE THREAD

**Issue by chelsEg** [tarantool-php/mapper#28]
Hello.

I have bug with sequence plugin where sequence is created by [create_index](https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_space/create_index/#box-space-create-index) with **sequence** option **true**.

My code:

```
$mapper->getSchema()->createSpace('some_space', [
    'is_sync'       => true,
    'if_not_exists' => true,
    'engine'        => 'memtx',
    'properties' => [
        'id'       => 'unsigned',
        'value'    => 'string',
    ],
])
->addIndex([
    'fields'        => 'id',
    'if_not_exists' => true,
    'sequence'      => true,
]);

$mapper->getPlugin(Tarantool\Mapper\Plugin\Sequence::class);
$result = $mapper->create('some_space', ['value'  => $value]);
```

**Exception:**

```
eval:1: variable 'mapper_create_sequence' is not declared {"exception":"[object] (Tarantool\\Client\\Exception\\RequestFailed(code: 32): eval:1: variable 'mapper_create_sequence' is not declared at /application/vendor/tarantool/client/src/Exception/RequestFailed.php:32)
[stacktrace]
#0 /application/vendor/tarantool/client/src/Handler/DefaultHandler.php(48): Tarantool\\Client\\Exception\\RequestFailed::fromErrorResponse(Object(Tarantool\\Client\\Response))
#1 /application/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(63): Tarantool\\Client\\Handler\\DefaultHandler->handle(Object(Tarantool\\Client\\Request\\EvaluateRequest))
#2 /application/vendor/tarantool/client/src/Middleware/AuthenticationMiddleware.php(41): Tarantool\\Client\\Handler\\MiddlewareHandler->handle(Object(Tarantool\\Client\\Request\\EvaluateRequest))
#3 /application/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(69): Tarantool\\Client\\Middleware\\AuthenticationMiddleware->process(Object(Tarantool\\Client\\Request\\EvaluateRequest), Object(Tarantool\\Client\\Handler\\MiddlewareHandler))
#4 /application/vendor/tarantool/client/src/Middleware/RetryMiddleware.php(72): Tarantool\\Client\\Handler\\MiddlewareHandler->handle(Object(Tarantool\\Client\\Request\\EvaluateRequest))
#5 /application/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(69): Tarantool\\Client\\Middleware\\RetryMiddleware->process(Object(Tarantool\\Client\\Request\\EvaluateRequest), Object(Tarantool\\Client\\Handler\\MiddlewareHandler))
#6 /application/vendor/tarantool/client/src/Client.php(170): Tarantool\\Client\\Handler\\MiddlewareHandler->handle(Object(Tarantool\\Client\\Request\\EvaluateRequest))
#7 /application/vendor/tarantool/mapper/src/Plugin/Procedure.php(50): Tarantool\\Client\\Client->evaluate('return _G.mappe...')
#8 /application/vendor/tarantool/mapper/src/Plugin/Procedure.php(43): Tarantool\\Mapper\\Plugin\\Procedure->validatePresence(Object(Tarantool\\Mapper\\Procedure\\CreateSequence))
#9 /application/vendor/tarantool/mapper/src/Plugin/Procedure.php(15): Tarantool\\Mapper\\Plugin\\Procedure->register('Tarantool\\\\Mappe...')
#10 /application/vendor/tarantool/mapper/src/Plugin/Sequence.php(47): Tarantool\\Mapper\\Plugin\\Procedure->get('Tarantool\\\\Mappe...')
#11 /application/vendor/tarantool/mapper/src/Plugin/Sequence.php(58): Tarantool\\Mapper\\Plugin\\Sequence->initializeSequence(Object(Tarantool\\Mapper\\Space))
#12 /application/vendor/tarantool/mapper/src/Plugin/Sequence.php(21): Tarantool\\Mapper\\Plugin\\Sequence->generateValue(Object(Tarantool\\Mapper\\Space))
#13 /application/vendor/tarantool/mapper/src/Repository.php(81): Tarantool\\Mapper\\Plugin\\Sequence->generateKey(Object(Tarantool\\Mapper\\Entity), Object(Tarantool\\Mapper\\Space))
#14 /application/vendor/tarantool/mapper/src/Mapper.php(45): Tarantool\\Mapper\\Repository->create(Array)
#15 /application/app/Components/Category/Repositories/CategoryRepository.php(40): Tarantool\\Mapper\\Mapper->create('some_space', Array)
"}
```

**Tarantool version:** 2.6.2
**PHP version:** 7.4.19

**UPD:**
This bug happened because sequence name is **space_name_seq**, but in your code you suppose sequence name is **space_name**.

**Comment by nekufa** [comment]
Hello, @chelsEg.
This happens because sequence plugin was written some time before sequences were implemented in tarantool.
I need to test it on our environment and see how we can support native tarantool sequence names.

**Comment by nekufa** [comment]
@chelsEg checkout 4.6.17 release

**Comment by chelsEg** [comment]
> @chelsEg checkout 4.6.17 release

Sequence created by Tarantool is works 👍 

But, I'm recommend You see on function **findOrCreate**!

Thanks for You fix!

**Comment by nekufa** [comment]
thanks, now that is fixed too :)
